-- +goose Up
CREATE TABLE IF NOT EXISTS products (
 id BIGSERIAL PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 price_in_centers INTEGER NOT NULL CHECK (price_in_centers > 0),
 quantity INTEGER NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

-- +goose Down
DROP TABLE IF EXISTS products;
