// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID             int64            `json:"id"`
	Name           string           `json:"name"`
	PriceInCenters int32            `json:"price_in_centers"`
	Quantity       int32            `json:"quantity"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}
