// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	GetProductById(ctx context.Context, id int64) (Product, error)
	GetProducts(ctx context.Context) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
